# -*- coding: utf-8 -*-
"""
created by Patrick O'Hara

Used to determine relative Abundance of Geobacter, Shewanella, Desulfo, Methano,
Methylo and Verruc prefixed bacteria and archea at depth within samples taken 
from Second Creek, MN.

Input files should be generated by Mothur before hand and should be located 
within the same folder the python script/class are located.

Mothur files need to run program: .SHARED and .TAXONOMY
    
    files should be written as strings within the Relative_Abundance script with
    the .SHARED file set to object named Shared and .TAXONOMY file set to object
    named Tax.

Location Should be input as a string and assigned to object named location.

example files have been provided

locations are dependent on the Mothur files. locations associated with example
file are: C3,C4,C5,C6,W3,W4,W5,W6

"""

import Relative_Abundance_class as ra

Shared = 'second_creek_V4_all.shared'
Tax = 'second_creek_V4_all.taxonomy'
location = 'C3'

instance = ra.Relative_Abundance(Shared,Tax,location)

instance.tab_2_csv()
instance.pull_OTUs()
instance.set_location_depth()
instance.plot_relative_abundance()